### ISSUE TITLE
Remote Debugging with pycharm

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#103]
Setting up the PyDev debugger

Run->Edit Configurations 
Right-Click Python, then click Add Configuration 
Select Python Remote Debug 
Change the name to "Debug on Localhost 678" 
Set Local host name to "localhost" 
Set port to "678" 
Click OK 
In the dropdown under the menu, select "Debug on Localhost 678"
 
Then click the insect with a right-arrow pointing out of it. That's the "Debug" button. You now have a debug server running on port 678 
Start a Python Script using pydevd: 
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 1.5.4\helpers\pydev\pydevd.py" --client 127.0.0.1 --port 678 --file D:/__empty_delete_me/run.py

If you can get pydevd running in IronPython, you'll be a hero and somebody will make you a cheese statue.

  - Brian

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-24767
