### ISSUE TITLE
Bug rs.OffsetSurface

### ISSUE THREAD

**Issue by 5chmidt** [mcneel/rhinoscriptsyntax#104]
In attempting to offset a NURBS surface only the value of None is returned.

```python
import rhinoscriptsyntax as rs

face=rs.GetSurfaceObject("Select Face")
OffDist=rs.GetReal("Specify Offset Distance",1.5)
Face=face[0]
Test=rs.IsSurface(Face)
if Test==True:
    OffsetSrf=rs.OffsetSurface(Face,OffDist)
    if OffsetSrf==None:
        OffsetSrf=rs.OffsetSurface(Face,-OffDist)
print OffsetSrf
```
Reference to Rhino Python Forum post with sample NURBS surface which does not work.
http://python.rhino3d.com/threads/1260-Offset-Surface-Issues?highlight=5chmidt

Thanks,
5chmidt

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30060
