### ISSUE TITLE
BrowseForFolder() ignores 'title'

### ISSUE THREAD

**Issue by westhom** [mcneel/rhinoscriptsyntax#113]
So, [BrowseForFolder()](https://github.com/mcneel/rhinopython/blob/master/scripts/rhinoscript/userinterface.py#L12) ignores the title option, and after investigating it doesn't look like it's possible to set the title of this dialog type due to .NET restrictions.

Edit [removed code]: just realized 'message' sets the dialog's description. Title should probably just be removed from params.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-28624
