### ISSUE TITLE
IsGroupEmpty

### ISSUE THREAD

**Issue by defterGoose** [mcneel/rhinoscriptsyntax#127]
This function returns the opposite of what one might expect: true for a full group, false for an empty one.

def IsGroupEmpty(group_name):
    """Verifies that an existing group is empty, or contains no object members
    Parameters:
      group_name = the name of an existing group
    Returns:
      True or False if group_name exists
      None if group_name does not exist
    """
    if not isinstance(group_name, str): group_name = str(group_name)
    index = scriptcontext.doc.Groups.Find(group_name, True)
    if index<0: return scriptcontext.errorhandler()
    return not scriptcontext.doc.Groups.GroupObjectCount(index)>0

Not in last line fixes it.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30065
