### ISSUE TITLE
Implementing some of the missing rhinoscriptsyntax functions?

### ISSUE THREAD

**Issue by stgeorges** [mcneel/rhinoscriptsyntax#132]
When can we expect to have some of these functions implemented in Python:

ReverseSurface, SetAttributeData, SetObjectData, ShearObject, ShearObjects, SimplifyArray...

I imagine there is a way of doing all these directly through RhinoCommon, but it would be nice if you could at least provide them through rhinoscript functions.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30067
