### ISSUE TITLE
FilletSurfaces raising an error: "Could not convert None to a Point2d"

### ISSUE THREAD

**Issue by stgeorges** [mcneel/rhinoscriptsyntax#134]
An issue arose at grasshooper forum, on supplying the rs.FilletSurfaces() function with uvparam0 and uvparam1 argument's default values (None):

http://www.grasshopper3d.com/forum/topics/can-we-use-filletsurfaces

Is that the correct solution or not?

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30068
