### ISSUE TITLE
OffsetSurface no longer working with trimmed surfaces

### ISSUE THREAD

**Issue by hstehling** [mcneel/rhinoscriptsyntax#143]
commit bac1a13f8ca0a7a8496a7adb4c9b9510cb0091ff prevents OffsetSurface from working with trimmed one-face breps ("trimmed surfaces"). Is this the desired effect? I imagine it will break a lot of people's scripts.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30071
