### ISSUE TITLE
Example code errors in "Rhino Python Primer" Documentation pg 53

### ISSUE THREAD

**Issue by anthoq88** [mcneel/rhinoscriptsyntax#148]
On page 53 of the "Rhino Python Primer" pdf doc - there is an off by one error in the example code:

    arrSubD.append(arrV[len(arrV)])

Comments don't use the character '#'

And 'PolylineLength' is both the name of a variable and a function

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30073
