### ISSUE TITLE
Storing Data In Rhino File

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#16]
http://python.rhino3d.com/threads/508-Storing-Data-in-a-Rhino-File

We need a mechanism for embedding data in a 3dm file beyond just strings.  I think the best way to do this would be to add support for embedded of any file type directly in a 3dm and have a way to access/create these files.  This would allow the python scripter to use something like pickle to embed custom data.

**This is a concept of how the embedded file system would work.**
**I haven't come up with an interface for this yet in RhinoCommon so it may change while I work out the details**

```python
import cPickle as pickle
import scriptcontext
import Rhino

data1 = Rhino.Geometry.Point3d(1,2,3)
selfref_list = [1, 2, 3]
selfref_list.append(selfref_list)

#output = open("C:\\test.pkl", "wb")
output = scriptcontext.doc.EmbeddedFiles.Open("test.pkl", "wb")

# Pickle dictionary using protocol 0.
pickle.dump(data1, output)

# Pickle the list using the highest protocol available.
pickle.dump(selfref_list, output, -1)

output.close()

#pkl_file = open('C:\\test.pkl', 'rb')
pkl_file = scriptcontext.doc.EmbeddedFiles.Open("test.pkl", "rb")

data1 = pickle.load(pkl_file)
print data1

data2 = pickle.load(pkl_file)
print data2

pkl_file.close()
```

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30033
