### ISSUE TITLE
Locks up when debugging

### ISSUE THREAD

**Issue by pgolay** [mcneel/rhinoscriptsyntax#19]
Sometimes when I'm in the middle of debugging a script, the editor appears to lock up and continues to think that it is debugging. I have to restart Rhino to fix this.
To reproduce, at least some times, set a break point and when you hit it in debugging, select some text in the editor and Delete or backspace, then type a couple of characters, Nothing happens, so then remember that you are debugging and click RunToEnd. That should lock it up.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30034
