### ISSUE TITLE
autosave / autobackup

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#22]
From Marc Fornes...
autosave is tricky when in development mode (trying things one might not want to save)
we talked about how the auto save when execute was an issue as over writing the file with the current test...
 
but it did now happen to me a few time that developing in a new file (not saved before) it crashed and therefore lost everything.
so I am guessing an autback type of file could be useful - where the code got saved in a mirror file that can be access when crashed - could even be the same file that you use to save when press execute...

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30035
