### ISSUE TITLE
import autocomplete list tuneup

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#30]
Most people use the syntax of
```python
import rhinoscriptsyntax
```
and there is no need to confuse them with the "rhinoscript" package which is essentially the same thing but in a "package" form.  Remove this from the autocomplete in the UI.

There are also a lot of other modules/packages not showing up in the autocomplete list.  These should get added if they make sense.

**Comment by acormier** [comment]
not an issue anymore
