### ISSUE TITLE
Module Browser updates

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhinoscriptsyntax#31]
Here are a few browser updates that may make it easier to discover new functions in Python:

- Under scriptcontext, the doc should have the methods and functions of Rhino.RhinoDoc listed in the tree. http://www.rhino3d.com/5/rhinocommon/html/T_Rhino_RhinoDoc.htm.  Currently this class looks like a place holder only.
- Under scriptcontext the sticky needs to have the dict methods listed. http://docs.python.org/library/stdtypes.html#mapping-types-dict.  Currenlty this dictionary looks lik a place holder only.
- Not sure if this is useful, but a branch of Python built in types would be useful. The syntax for If, elif, while etc.. while simple, is good to see and remind the beginner.
- Should math, random and datetime be listed under python? Perhaps add built in under there.

Can I doubleclick or right click to add an Import.... for any of theses commonly used modules into my script?

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30037
