### ISSUE TITLE
rhinoscriptsyntax documentation

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhinoscriptsyntax#32]
The online documentation for rhinoscriptsyntax may need to be updated:

I believe this is the proper link - http://www.rhino3d.com/5/ironpython/index.html

- In the browser the rhinoscriptsyntax should be added, or rhinoscript Package should be renamed in this browser to rhinoscriptsyntax.
- When I select rhinoscript Package in the browser, I get the page http://www.rhino3d.com/5/ironpython/rhino_package.htm on the right.  The terminology introduction says "The Rhino Package"  It should say rhinoscriptsyntax package.  The naming in the short paragraph below should also be updated to reference rhinoscriptsyntax package and not Rhino.
- The module links on this page http://www.rhino3d.com/5/ironpython/rhino_package.htm do not link the to proper module pages.  They are dead links.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30039
