### ISSUE TITLE
Old Wishes from Giulio

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#35]
This has been sitting in my email for over a year, so some of the items have already been fixed.  Moving to github issues so I don't lose them.

1.       mouse-wheel scrolling one document make other documents in the background scroll, too
2.       scrolling is now enabled even when there’s no scrollbar. Isn’t that a bit confusing?
3.       Ctrl+F opens “find and replace”. That’s very good. Then, though, if one uses that window it’s almost impossible to see the selected text. If one closes that window, then the selection with F3 is on gray background and it’s all good
4.       Wish: pushing F1 on the v4  _EditScript editor opens the help file at the right page, if the text cursor is on a RhinoScript keyword (like Rhino.AddLine). Could this work in IronPython and Monkey? (this never worked on Monkey and it is a great feature I think, my biggest wish)
5.       Wish: Do you think it would be taking a long time to write code to visualize which open parenthesis one closes when one writes “)”?
6.       Wish: possibility to close the left control completely
7.       Wish: double-clicking a method in the left control opens the Help at the right page (I know it writes text in the output – I find this would be still a plus)

I know you have a lot of projects already, so really just take the wishes as small suggestions.

Thanks,
- Giulio

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30041
