### ISSUE TITLE
RhinoscriptSytax for GHPython

### ISSUE THREAD

**Issue by scotttd** [mcneel/rhinoscriptsyntax#45]
There are two data types that we may need a RhinoScriptsytax method to create.  It is important we can create these, for when I simple output these object types as lists out of a Grasshopper component, they are output as a list of values, individual members.  I cannot hold the object together as a list unless I am able to instantiate the object.

Interval -- This is a popular datatype in Grasshopper, but does not exist in Rhinoscriptsyntax. I realize I can create an interval by including the Rhino namespace and calling down into the geometry class.

b = rh.geometry.interval(1.0,4.0)

this forces you down the track of importing the Rhino namespace and calling into the class. Is it worth having a call:

b = rs.createinterval(1.0,4.0)

Domain -- A domain is a 2 dimensional interval for UV domains. Also used in Grasshopper.  I cannot even find this type in RhinoCommon.  Do we need a:

rs.createdomain((1.0,4.0),(2.6, 5.0))

Then I can pass that domain out to a domain to grasshopper.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30045
