### ISSUE TITLE
Editor with custom templates

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#59]
From python forum  http://python.rhino3d.com/threads/692-Wish-Editor-with-custom-templates

Hi Steve,

if you open a new script, you are asked if you would like to create a command or an empty script.

It would be great to be able to add additional options to that dialogs with my custom designed code layout.

- Martin

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30052
