### ISSUE TITLE
Autosave causing problems

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#72]
From the python forum
http://python.rhino3d.com/threads/820-Autosave-before-running-a-file-in-the-editor-(

Autosave before running a file in the editor :(
I'm really beginning to hate this "feature"... If I'm experimenting with stuff and I make a bunch of changes to a file they all get saved and there's no way to "revert" without doing ctrl+Z - * a zillion times, as it goes letter-by-letter. Can't the changes get saved in the background to a temp file with option to revert? Or keep the last saved version as a backup and have a "revert to saved" button?

And if you make the mistake of hitting the close button... the file closes without asking (as it has been saved by running it the last time) and all your undos are lost. 

It just seems wrong to me to overwrite the last saved version automatically without asking the user...

--Mitch

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30035
