### ISSUE TITLE
Add Radial Dimension + Add Angular Dimension 

### ISSUE THREAD

**Issue by gwinsky** [mcneel/rhinoscriptsyntax#73]
Hi Steve,
Can you put this on the wishlist?
it would be useful to have methods for:

•Add Radial Dimension 
•Add Angular Dimension 

in RhCommon and ideally also in rhinoscriptsyntax.

I could not find it here:
http://www.rhino3d.com/5/rhinocommon/html/AllMembers_T_Rhino_DocObjects_Tables_ObjectTable.htm

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30054
