### ISSUE TITLE
SetIsoCurve python function inconsistency

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#80]
email from Pascal
Hi Steve- on SurfaceIsocurveDensity, it seems to me things do not quite 
match the descriptions:

Density Optional.  Number.  The isocurve wireframe density.  The 
possible values are as follows:

"-1 Hides surface isocurves."

If I set -1, properties does not uncheck the Visible box and sets the 
number to 0.

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30055
