### ISSUE TITLE
Allow paste into search path list

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinoscriptsyntax#87]
http://python.rhino3d.com/threads/978-Setting-paths-to-Python-scripts-from-the-editor

Hi Steve,

We need the possibility to paste in a pre-concocted path, currently one always has to browse to the folder via the "+" button... 

But... 
What we really need is this to get integrated into the main Rhino>Options interface. Either paths entered in Options>Files>Search Paths get automatically transferred over to Python, or perhaps a separate Python section like Rhinoscript has in Options already... I guess that the possibility to have Python startup scripts also need to be integrated into there...

Thanks, --Mitch

**Comment by acormier** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-29209
